#' Computed the RV coefficient between the metrics.
#'
#' `RV_COR()` Return matrix of correlation between all metrics.
#'
#' This function is meant to be used with the tab generated by formultivariate()
#' The RV coefficient is meant to compute the correlation between two tabs.
#' In this case metric's values at each scale are considered as tab. So a RV coefficient is computed
#' for each pairwise metrics with an associeted p-value.
#' @param Varia_paysage_multi Tab generated by formultivariate()
#'
#' @param dist Vector of scales you choosed during you analusis in Chloe
#' @param metrics Vector of  metrics  you choosed in Chloe during your analysis in Chloe
#' @return Return matrix of correlation between all metrics.
#' @export
RV_COR=function(Varia_paysage_multi,metrics,dist){
  coefRV=matrix(ncol=length(metrics),nrow=length(metrics))
  pvalue=matrix(ncol=length(metrics),nrow=length(metrics))

  seq_group=seq(4,ncol(Varia_paysage_multi)+1,length(dist))

  pb <- txtProgressBar(min = 0, max = length(seq_group), style = 3)

  for (i in 1:(length(seq_group)-1)) {
    Sys.sleep(0.1)
    setTxtProgressBar(pb, i)
    for (j in 1:(length(seq_group)-1)) {
      temp=coeffRV(Varia_paysage_multi[,seq_group[i]:(seq_group[i+1]-1)],Varia_paysage_multi[,seq_group[j]:(seq_group[j+1]-1)])
      coefRV[i,j]=temp$rv
      pvalue[i,j]=temp$p.value

    }
  }

  colnames(coefRV) <- rownames(coefRV)<- metrics
  colnames(pvalue) <- rownames(pvalue)<- metrics
  return(list(coefRV,pvalue))
}
